// Skills data — add/remove entries here to update the skills grid
// icon: { type: 'svg'|'png'|'webp', name: 'filename-without-ext' }
// skillLevel: 0-100 (current), reachedSkillLevel: 0-100 (peak)
// useReachedFirst: true = opacity based on reachedSkillLevel ?? skillLevel (default)
// highlighted: true = shown when minimize is active (others appear only when expanded)
// learning: true = show pink dot
// notUsedForYears: true = opacity 0.1, orange dot + "not working on it for years" tooltip badge
// forgotButCanRelearnIn: string = show green bar + tooltip text
// iconSize: Tailwind size classes for the icon, e.g. 'size-10' or 'h-7 w-9'
//           (default 'h-10 w-10', or 'h-9 w-9' for the no-icon fallback)

const SKILLS = [
  {
    title: 'Java',
    description: 'Java is a popular programming language for building enterprise applications. It is a high-level, class-based, object-oriented language. Java is first designed to be make easy to develop platform-independent application GUIs. I actually don\'t like java much because of its OOP design. I prefer kotlin instead.',
    icon: { type: 'svg', name: 'java' },
    reachedSkillLevel: 40,
    type: 'Language',
    notUsedForYears: true,
  },
  {
    title: 'TypeScript',
    description: 'I usually use Typescript for writing Javascript. It sometimes helping me to see problematic code in my editor with its special warnings and errors.',
    icon: { type: 'svg', name: 'typescript' },
    skillLevel: 100,
    type: 'Language',
    highlighted: true,
  },
  {
    title: 'JavaScript',
    description: 'While I can work with plain JavaScript, I prefer TypeScript and I know they are pretty much same thing.',
    icon: { type: 'svg', name: 'javascript' },
    skillLevel: 100,
    type: 'Language',
    highlighted: true,
  },
  {
    title: 'Webflow',
    description: 'Webflow is a website builder for creating designer-friendly websites.',
    icon: { type: 'svg', name: 'webflow' },
    iconSize: 'size-10',
    skillLevel: 100,
    type: 'Tool',
    highlighted: true,
  },
  {
    title: 'GSAP',
    description: 'GSAP is a highly customizable Javascript animation library.',
    icon: { type: 'svg', name: 'gsap' },
    skillLevel: 100,
    type: 'Library-framework',
    highlighted: true,
  },
  {
    title: 'C',
    description: "Mother of most high-level programming languages. I love C more than myself, its the best language so far. I wish had more time to learn it...",
    icon: { type: 'svg', name: 'c' },
    skillLevel: 55,
    type: 'Language',
    learning: true,
    highlighted: true,
  },
  {
    title: 'Kotlin',
    description: 'Kotlin is a modern programming language that is fully interoperable with Java. Kotlin makes easier to develop java applications.',
    icon: { type: 'svg', name: 'kotlin' },
    iconSize: 'size-10',
    reachedSkillLevel: 100,
    type: 'Language',
    forgotButCanRelearnIn: '1 week',
    notUsedForYears: true
  },
  {
    title: 'Kotlin Multiplatform (Android, Desktop)',
    description: 'Kotlin Multiplatform is a framework for building cross-platform applications with Kotlin.',
    icon: { type: 'png', name: 'kmp' },
    reachedSkillLevel: 100,
    type: 'Library-framework',
    forgotButCanRelearnIn: '1 week',
    notUsedForYears: true
  },
  {
    title: 'Ktor',
    description: 'Kotlin server framework for building server applications with Kotlin. Very similar to express.js.',
    icon: { type: 'png', name: 'ktor' },
    reachedSkillLevel: 100,
    type: 'Library-framework',
    forgotButCanRelearnIn: '1 week',
    notUsedForYears: true
  },
  {
    title: 'Jetpack Compose',
    description: 'Jetpack compose is a modern UI library for building native java/kotlin applications.',
    icon: { type: 'svg', name: 'jetpackcompose' },
    iconSize: 'size-10',
    reachedSkillLevel: 100,
    type: 'Library-framework',
    forgotButCanRelearnIn: '1 week',
    notUsedForYears: true
  },
  {
    title: 'Room database',
    description: 'SQLite database ORM library for Android developed by Google.',
    icon: { type: 'svg', name: 'android' },
    reachedSkillLevel: 50,
    type: 'Database',
    forgotButCanRelearnIn: '2 days',
    notUsedForYears: true
  },
  {
    title: 'SQLDelight',
    description: 'SQLDelight is a type-safe SQL library for Kotlin. It does the opposite of ORMs does. Instead of generating SQL from your code models, it generates type-safe kotlin models from your SQL code.',
    icon: { type: 'png', name: 'sqldelight' },
    reachedSkillLevel: 100,
    type: 'Database',
    notUsedForYears: true
  },
  {
    title: 'Gradle',
    description: 'I fucking hate gradle. Just putting it here to say that.',
    icon: { type: 'svg', name: 'gradle' },
    type: 'Tool',
  },
  {
    title: 'Lua',
    description: 'Lua is very good scripting language. I really like it.',
    icon: { type: 'svg', name: 'lua' },
    skillLevel: 3,
    type: 'Language',
    learning: true,
  },
  {
    title: 'OpenGL',
    description: 'I started interested in OpenGL after seeing how all of the modern game engines trying to be are high level, user friendly and OOP. I want to learn how Graphics Processing Units and Central Processing Units works with each other and how manufacturers designs their card around OpenGL spesification in the low level surface. Still learning it :> Edit: OH GOD WHY ITS SO DIFFUCULT TO DRAW A BASIC TRIANGLE',
    icon: { type: 'svg', name: 'opengl' },
    reachedSkillLevel: 2,
    type: 'API',
    learning: true,
  },
  {
    title: 'Raylib',
    description: 'Raylib is a simple and easy-to-use library to enjoy videogames programming. Actually I know how raylib works do lot of stuff in it but I\'m trying to learn everything about it and wanna use raw opengl with it.',
    icon: { type: 'png', name: 'raylib' },
    skillLevel: 80,
    type: 'Library-framework',
    learning: true,
    iconSize: 'size-10',
    highlighted: true,
  },
  {
    title: 'Python',
    description: 'Very basic, high-level, not-scalable, educational, toy, annoying programming language.',
    icon: { type: 'svg', name: 'python' },
    skillLevel: 100,
    type: 'Language',
    notUsedForYears: true
  },
  {
    title: 'Gemini API',
    description: 'I can use gemini API efficently by using fine tunning and applying Retrieval-augmented generation (RAG) techniques.',
    icon: { type: 'svg', name: 'gemini' },
    type: 'API',
  },
  {
    title: 'Openrouter',
    description: 'Openrouter is a very good API service which gives you accesss to all the AI models with one API call. Without openrouter, its really hard to maintain multiple Cloud service providers to use different models at the same time.',
    icon: { type: 'png', name: 'openrouter' },
    skillLevel: 100,
    type: 'API',
  },
  {
    title: 'Flask',
    description: 'Python web framework for building web applications and APIs. Similar to express.js, fastify and ktor.',
    icon: { type: 'svg', name: 'flask' },
    skillLevel: 80,
    type: 'Library-framework',
  },
  {
    title: 'Google Colab',
    description: 'Google Colab is a free Jupyter notebook environment.',
    icon: { type: 'svg', name: 'colab' },
    type: 'Dev tool',
  },
  {
    title: 'CSS3',
    description: 'Web design language for styling and layouting html pages.',
    icon: { type: 'svg', name: 'css-3' },
    skillLevel: 100,
    type: 'Language',
    highlighted: true,
  },
  {
    title: 'SCSS',
    description: null,
    icon: { type: 'svg', name: 'scss' },
    skillLevel: 90,
    type: 'Language',
  },
  {
    title: 'Tailwind CSS',
    description: 'My preferred CSS library for building responsive and maintainable user interfaces with utility-first approach.',
    icon: { type: 'svg', name: 'tailwind' },
    skillLevel: 100,
    type: 'Library-framework',
  },
  {
    title: 'React',
    description: 'My primary web frontend library for building dynamic user interfaces.',
    icon: { type: 'svg', name: 'react' },
    skillLevel: 100,
    type: 'Library-framework',
    highlighted: true,
  },
  {
    title: 'React Native',
    description: 'Simple way to build basic mobile applications with React.',
    icon: { type: 'svg', name: 'react' },
    reachedSkillLevel: 100,
    type: 'Library-framework',
    forgotButCanRelearnIn: '4 days',
    highlighted: true,
    notUsedForYears: true
  },
  {
    title: 'Expo',
    description: 'A powerful framework built around React Native that simplifies mobile app development.',
    icon: { type: 'svg', name: 'expo' },
    reachedSkillLevel: 100,
    type: 'Library-framework',
    forgotButCanRelearnIn: '4 days',
    highlighted: true,
    notUsedForYears: true
  },
  {
    title: 'Next.js',
    description: 'Full-stack React framework for applications with features like server-side rendering, API routes, and optimized performance.',
    icon: { type: 'png', name: 'nextjs' },
    skillLevel: 100,
    type: 'Library-framework',
    highlighted: true,
  },
  {
    title: 'Turborepo',
    description: 'Monorepo management tool for JavaScript and TypeScript projects.',
    icon: { type: 'png', name: 'turbo' },
    reachedSkillLevel: 100,
    type: 'Library-framework',
    forgotButCanRelearnIn: '3 hours',
  },
  {
    title: 'React Query',
    description: 'Powerful data-fetching library for React that handles caching, synchronization, and server state management with features like automatic background updates and optimistic updates.',
    icon: { type: 'svg', name: 'react-query' },
    skillLevel: 100,
    type: 'Library-framework',
    highlighted: true,
  },
  {
    title: 'Better Auth',
    description: 'Typesafe, customizable and easy authentication library for Typescript and Javascript applications.',
    icon: { type: 'svg', name: 'better-auth', rounded: true },
    type: 'Library-framework',
    notUsedForYears: true
  },
  {
    title: 'JWT',
    description: 'JSON Web Token (JWT) is an encryption method for generating authentication tokens. These tokens can be used to verify the identity of a user and grant access to protected resources.',
    icon: { type: 'svg', name: 'jwt', darkBg: true },
    type: 'Other',
  },
  {
    title: 'Encryption algorithms I used',
    description: 'AES 256, RSA, GCM, TIGER, SHA-256, SHA-512, PADDING, HMAC, PBKDF2, Bcrypt, Argon2, and more.',
    icon: { type: 'svg', name: 'key', darkBg: true },
    skillLevel: 100,
    type: 'Other',
  },
  {
    title: 'HCaptcha',
    description: 'HCaptcha is a bot protection, human verification, and CAPTCHA service.',
    icon: { type: 'svg', name: 'hcaptcha' },
    type: 'Service',
    iconSize: 'size-10'
  },
  {
    title: 'Node.js',
    description: 'Node.js is a Javascript backend runtime for building server-side applications.',
    icon: { type: 'svg', name: 'nodejs' },
    skillLevel: 100,
    type: 'Library-framework',
    highlighted: true,
  },
  {
    title: 'WebSocket',
    description: 'Protocol for full-duplex communication channels over TCP connection.',
    icon: { type: 'svg', name: 'websocket' },
    skillLevel: 100,
    iconSize: 'size-10',
    type: 'API',
  },
  {
    title: 'Socket.io',
    description: 'Library for creating websocket server using node.js.',
    icon: { type: 'svg', name: 'socket' },
    skillLevel: 100,
    iconSize: 'size-10',
    type: 'API',
    notUsedForYears: true,
  },
  {
    title: 'WebRTC',
    description: 'Technology for real-time communication of audio, video, and data in web browsers.',
    icon: { type: 'svg', name: 'webrtc' },
    skillLevel: 60,
    type: 'API',
    notUsedForYears: true,
    highlighted: true,
  },
  {
    title: 'tRPC',
    description: 'End-to-end typesafe API layer, perfect for full-stack TypeScript projects. Best when client and server code live together for maximum type safety.',
    icon: { type: 'png', name: 'trpc', rounded: true },
    skillLevel: 100,
    type: 'API',
    notUsedForYears: true,
  },
  {
    title: 'GraphQL',
    description: 'Query language for APIs, ideal when client and server are separate. Provides type safety data fetching and mutations.',
    icon: { type: 'svg', name: 'graphql' },
    skillLevel: 90,
    type: 'API',
  },
  {
    title: 'Express.js',
    description: 'Express is a high level node.js http server framework. I can also use fastify, hono, ktor and other similar technologies easily.',
    icon: { type: 'svg', name: 'express' },
    skillLevel: 100,
    type: 'Library-framework',
  },
  {
    title: 'PostgreSQL',
    description: 'Powerfull relational database. I\'m using it for complex queries, data structres.',
    icon: { type: 'svg', name: 'postgresql' },
    skillLevel: 100,
    type: 'Database',
  },
  {
    title: 'Clerk',
    description: 'Easiest way to add authentication to your app with just a few lines of code.',
    icon: { type: 'svg', name: 'clerk', rounded: true },
    type: 'Service',
    iconSize: 'size-10'
  },
  {
    title: 'Neon',
    description: 'Postgres database provider service.',
    icon: { type: 'png', name: 'neon', rounded: true },
    type: 'Service',
    notUsedForYears: true,
    iconSize: 'size-10',
    notUsedForYears: true
  },
  {
    title: 'Xata',
    description: 'Postgres database provider service.',
    icon: { type: 'svg', name: 'xata', rounded: true },
    type: 'Service',
    iconSize: 'size-10',
    notUsedForYears: true
  },
  {
    title: 'Vercel',
    description: 'Platform for deploying and hosting web applications with automatic CI/CD.',
    icon: { type: 'svg', name: 'vercel' },
    skillLevel: null,
    type: 'Service',
    iconSize: 'size-10'
  },
  {
    title: 'Cloudflare',
    description: 'Web infrastructure and security services including CDN, DNS, and DDoS protection.',
    icon: { type: 'svg', name: 'cloudflare' },
    skillLevel: null,
    type: 'Service',
  },
  {
    title: 'upstash',
    description: "I've used their redis service for a while. It's a great service.",
    icon: { type: 'svg', name: 'upstash', rounded: true },
    type: 'Service',
    iconSize: 'size-10'
  },
  {
    title: 'MySQL',
    description: 'One of the most popular relational databases.',
    icon: { type: 'svg', name: 'mysql' },
    skillLevel: 40,
    type: 'Database',
  },
  {
    title: 'Chroma',
    description: 'Vector database for storing and querying vector data. Vector databases are used for machine learning and data analysis.',
    icon: { type: 'svg', name: 'chroma' },
    skillLevel: 60,
    type: 'Database',
  },
  {
    title: 'Milvus',
    description: 'Compared to Chroma, Milvus is more advanced vector database for building complex applications using machine learning, data analysis, search, and recommendation systems.',
    icon: { type: 'png', name: 'milvus', rounded: true },
    skillLevel: 30,
    type: 'Database',
    notUsedForYears: true
  },
  {
    title: 'SQLite',
    description: "Light, SQL database engine. I'm usually using for mobile applications.",
    icon: { type: 'svg', name: 'sqlite' },
    skillLevel: 100,
    type: 'Database',
    notUsedForYears: true
  },
  {
    title: 'Drizzle ORM',
    description: 'TypeScript ORM for SQL databases with a focus on type safety and developer experience. I prefer using drizzle instead of Prisma because it\'s more lightweight.',
    icon: { type: 'png', name: 'drizzle', rounded: true },
    skillLevel: 100,
    type: 'Database',
    notUsedForYears: true
  },
  {
    title: 'Prisma',
    description: 'Modern ORM for Node.js and TypeScript, providing type-safe database access and migrations.',
    icon: { type: 'svg', name: 'prisma' },
    type: 'Database',
    notUsedForYears: true,
    iconSize: 'size-10'

  },
  {
    title: 'Redis',
    description: 'In-memory database for caching, non persistent data storage and real-time data processing.',
    icon: { type: 'svg', name: 'redis' },
    skillLevel: 90,
    type: 'Database',
    iconSize: 'size-10',
    notUsedForYears: true
  },
  {
    title: 'Git',
    description: 'Version control system for tracking changes and collaborating on code projects.',
    icon: { type: 'svg', name: 'git' },
    skillLevel: 100,
    type: 'Tool',
    highlighted: true,
  },
  {
    title: 'Linux',
    description: 'I hate windows and mac or any other malware.',
    icon: { type: 'svg', name: 'linux' },
    type: 'Other',
  },
  {
    title: 'Vim',
    description: 'Vim is a terminal based highly advanced file editor. It really speeds up my coding speed because of its keybindings, customization.',
    icon: { type: 'svg', name: 'vim' },
    type: 'Dev tool',
    highlighted: true,
  },
  {
    title: 'Android Studio',
    description: "I'm using Android studio for developing kotlin-java applications. It's a powerful IDE with a wide range of features and plugins.",
    icon: { type: 'svg', name: 'androidstudio' },
    skillLevel: null,
    type: 'Dev tool',
    notUsedForYears: true
  },
  {
    title: 'Figma',
    description: 'Design tool for creating and implementing user interfaces and design systems.',
    icon: { type: 'svg', name: 'figma' },
    skillLevel: 100,
    type: 'Tool',
    highlighted: true,
  },
  {
    title: 'Vite',
    description: null,
    icon: { type: 'svg', name: 'vite' },
    type: 'Library-framework',
  },
  {
    title: 'Nginx',
    description: "Nginx is a reverse proxy server that sits in front of servers to handle incoming requests and distribute them to the appropriate servers. It can improve security, performance, and scalability. I use it to just host basic websites.",
    icon: { type: 'svg', name: 'nginx' },
    type: 'Tool',
  },
  {
    title: 'Docker',
    description: "I'm using Docker for containerizing applications, ensuring consistent development environments, and simplifying deployment processes.",
    icon: { type: 'svg', name: 'docker' },
    skillLevel: 100,
    type: 'Tool',
    iconSize: 'size-10'
  },
  {
    title: 'PHP',
    description: null,
    icon: { type: 'svg', name: 'php' },
    skillLevel: 0,
    reachedSkillLevel: 100,
    useReachedFirst: false,
    type: 'Language',
  },
  {
    title: 'Laravel',
    description: null,
    icon: { type: 'svg', name: 'laravel' },
    skillLevel: 0,
    reachedSkillLevel: 100,
    useReachedFirst: false,
    type: 'Library-framework',
    notUsedForYears: true
  },
  {
    title: 'RabbitMQ',
    description: null,
    icon: { type: 'svg', name: 'rabbitmq' },
    skillLevel: 5,
    reachedSkillLevel: 30,
    type: 'Library-framework',
    forgotButCanRelearnIn: '3 days',
    notUsedForYears: true
  },
];
